name: deluge-lukewh
version: 2.0.3
summary: Torrents
description: Torrents

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  deluge:
    plugin: python
    source: git://deluge-torrent.org/deluge.git
    source-tag: deluge-2.0.3
    requirements:
      - requirements.txt
    stage-packages:
      - python3-libtorrent
      - lsof
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av launcher.sh $SNAPCRAFT_PART_INSTALL/bin

apps:
  deluged:
    command: launcher.sh deluged
    plugs:
      - network
      - network-bind
  #deluge-console:
  #  command: bin/deluge-console
  deluge-web:
    command: launcher.sh deluge-web
    plugs:
      - network
      - network-bind
      - removable-media
  #deluge-gtk:
  #  command: bin/deluge-gtk
