name: deluge-lukewh
version: 2.0.5
summary: Torrents
description: Torrents

base: core18
grade: stable
confinement: strict

architectures:
  - build-on:
      - amd64
      - armhf
      - arm64
  - run-on:
      - amd64
      - armhf
      - arm64
      

parts:
  deluge:
    plugin: python
    source: git://deluge-torrent.org/deluge.git
    source-tag: deluge-2.0.5
    requirements:
      - requirements.txt
    stage-packages:
      - python3-libtorrent
      - lsof
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av launcher.sh $SNAPCRAFT_PART_INSTALL/bin

apps:
  deluged-service:
    command: launcher.sh -d -c deluged
    daemon: simple
    plugs:
      - network
      - network-bind
      - removable-media
  deluge-web-service:
    command: launcher.sh -d -c deluge-web
    daemon: simple
    plugs:
      - network
      - network-bind
  deluged:
    command: launcher.sh -c deluged
    plugs:
      - network
      - network-bind
      - removable-media
  #deluge-console:
  #  command: bin/deluge-console
  deluge-web:
    command: launcher.sh -c deluge-web
    plugs:
      - network
      - network-bind
  #deluge-gtk:
  #  command: bin/deluge-gtk
